# /a/b

[markdown]
group = "b"
title = "Get B without id"

summary = "This is to get 'b' without id"

[markdown.data.output]
type = "json"
content = '''{
    "content": "b"
}'''
note = '''
See [appendix-b](appendix.md#appendix-b)
'''

[openapi]
summary = "b"

[openapi.responses.200]
description = "A JSON array of user names"

[openapi.responses.200.content."application/json".schema]
type = "array"

[openapi.responses.200.content."application/json".schema.items]
type = "string"