# /a/b
group = "b"
title = "Get B without id"

summary = "This is to get 'b' without id"

[data.output]
type = "json"
content = '''{
    "content": "b"
}'''
note = '''
See [appendix-b](appendix.md#appendix-b)
'''