# /a/b

[markdown]
group = "b"
title = "Post b"

summary = "This is to post to 'b'"

[openapi_paths]
summary = "This is to post to 'b'"
operationId = "bPost"

[openapi_paths.responses.200]
description = "A JSON array of user names"

[openapi_paths.responses.200.content."application/json".schema]
type = "array"

[openapi_paths.responses.200.content."application/json".schema.items]
type = "string"