# /c

[markdown]
group = "c"
title = "Get c"

summary = "This is to get 'c'"

[openapi_paths]
summary = "This is to get 'c'"
operationId = "cGet"

[openapi_paths.responses.200]
description = "A JSON array of user names"

[openapi_paths.responses.200.content."application/json".schema]
type = "array"

[openapi_paths.responses.200.content."application/json".schema.items]
type = "string"