# /a/b

[markdown]
group = "b"
title = "Get B"

summary = "This is to get 'b'"

[markdown.data.output]
type = "json"
content = '''{
    "content": "b"
}'''
note = '''
See [appendix-c](appendix.md#appendix-c)
'''

[openapi_paths]
summary = "This is to get 'b'"
operationId = "bWithId"

[[openapi_paths.parameters]]
in = "path"
name = "id"
schema = { type = "integer" }
required = true
description = "User id"

[openapi_paths.responses.200]
description = "A JSON array of user names"

[openapi_paths.responses.200.content."application/json".schema]
type = "array"

[openapi_paths.responses.200.content."application/json".schema.items]
type = "string"