# /a/b

[markdown]
group = "b"
title = "Get B"

summary = "This is to get 'b'"

[markdown.data.output]
type = "json"
content = '''{
    "content": "b"
}'''
note = '''
See [appendix-c](appendix.md#appendix-c)
'''